apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "13"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"backend","namespace":"mrogern-tenorio-dev"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"backend"}},"template":{"metadata":{"labels":{"app":"backend"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","value":"postgres-service"},{"name":"DB_PORT","value":"5432"},{"name":"DB_NAME","valueFrom":{"secretKeyRef":{"key":"POSTGRES_DB","name":"postgres-secret"}}},{"name":"DB_USER","valueFrom":{"secretKeyRef":{"key":"POSTGRES_USER","name":"postgres-secret"}}},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"POSTGRES_PASSWORD","name":"postgres-secret"}}}],"image":"ghcr.io/marcustenorio/techroute-backend:latest","name":"backend","ports":[{"containerPort":8000}]}]}}}}
    kubernetes.io/change-cause: oc set image deployment/backend backend=ghcr.io/marcustenorio/techroute-backend:latest
      --record=true
  creationTimestamp: "2025-11-20T14:41:09Z"
  generation: 16
  name: backend
  namespace: mrogern-tenorio-dev
  resourceVersion: "5272135833"
  uid: d59ad679-fafe-4998-a929-0124871b60b8
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-21T22:37:34-03:00"
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: postgres-secret
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: postgres-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-secret
        image: ghcr.io/marcustenorio/techroute-backend:latest
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-11-21T13:17:36Z"
    lastUpdateTime: "2025-11-22T01:37:42Z"
    message: ReplicaSet "backend-56856ffb5c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-11-22T11:23:43Z"
    lastUpdateTime: "2025-11-22T11:23:43Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 16
