name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login no GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build da imagem Backend
      run: |
        IMAGE="ghcr.io/${{ github.actor }}/techroute-backend:${{ github.sha }}" 
        docker build -t "$IMAGE" backend
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Push da imagem para GHCR
      run: |
        docker push "$IMAGE"

    - name: Install oc CLI
      run: |
        curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz -o oc.tar.gz
        tar -xzvf oc.tar.gz
        sudo mv oc /usr/local/bin/oc
        sudo mv kubectl /usr/local/bin/kubectl
        sudo chmod +x /usr/local/bin/oc /usr/local/bin/kubectl
        oc version --client
 
    - name: Login no OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OC_SERVER }}
        openshift_token: ${{ secrets.OC_TOKEN }}
        insecure_skip_tls_verify: true

    - name: Atualizar Deployment no OpenShift
      run: |
        oc project ${{ secrets.OC_NAMESPACE }}
        oc set image deployment/backend backend="$IMAGE" --record

    - name: Aguardar rollout
      run: |
        oc rollout status deployment/backend

